---
- name: Deploy ActiveMQ on Minikube
  hosts: minikube
  become: true
  tasks:
    - name: Install kubectl
      apt:
        name: kubectl
        state: present

    - name: Install Minikube
      shell: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/

    - name: Start Minikube
      command: minikube start

    - name: Apply Nginx Ingress Controller
      kubectl:
        kubeconfig: ~/.kube/config
        src: nginx-ingress-controller.yml
        state: present

    - name: Apply Primary ActiveMQ deployment
      kubectl:
        kubeconfig: ~/.kube/config
        src: primary-activemq-deployment.yml
        state: present

    - name: Apply Backup ActiveMQ deployment
      kubectl:
        kubeconfig: ~/.kube/config
        src: backup-activemq-deployment.yml
        state: present

    - name: Apply ActiveMQ service
      kubectl:
        kubeconfig: ~/.kube/config
        src: activemq-service.yml
        state: present
