apiVersion: v1
kind: Service
metadata:
  name: backup-activemq
spec:
  type: ClusterIP
  selector:
    app: activemq
    role: backup
  ports:
    - protocol: TCP
      port: 61616
      targetPort: 61616
