apiVersion: v1
kind: Service
metadata:
  name: primary-activemq
spec:
  type: ClusterIP
  selector:
    app: activemq
    role: primary
  ports:
    - protocol: TCP
      port: 61616
      targetPort: 61616
